<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>DataUsage.Cli</RootNamespace>
    <AssemblyName>datausage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataUsage.Core\DataUsage.Core.csproj" />
  </ItemGroup>
</Project>
